# Generated by Django 5.1.7 on 2025-03-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of the Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the employee')),
                ('age', models.IntegerField(verbose_name='Age of the employee')),
                ('phone', models.IntegerField(verbose_name='Phone Number of the employee ')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.unit')),
            ],
        ),
    ]
