# Generated by Django 5.1.7 on 2025-03-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='NA', max_length=50, verbose_name='Designation of the employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='isHead',
            field=models.BooleanField(default=False, verbose_name='Is the head of the Unit?'),
            preserve_default=False,
        ),
    ]
