# Generated by Django 5.1.7 on 2025-03-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Traffic', 'Traffic'), ('Armed Forces', 'Armed Forces')], default='Civil', max_length=50),
        ),
    ]
