# Generated by Django 5.1.7 on 2025-03-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_unit_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
