# Generated by Django 5.1.7 on 2025-03-26 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the Items')),
                ('quantity', models.IntegerField(verbose_name='Quantity of the Items')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item_category')),
            ],
        ),
        migrations.CreateModel(
            name='Item_unit_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity of the items for the unit')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.unit')),
            ],
        ),
    ]
