# Generated by Django 5.1.7 on 2025-03-20 08:53

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0002_employee_designation_employee_ishead'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField(verbose_name='Age of the employee')),
                ('phone', models.IntegerField(verbose_name='Phone Number of the employee ')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation of the employee')),
                ('isHead', models.BooleanField(verbose_name='Is the head of the Unit?')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.unit')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
